# Generated by Django 4.1.7 on 2023-03-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('familiya', models.CharField(help_text='Фамилия', max_length=50)),
                ('imya', models.CharField(help_text='Имя', max_length=50)),
                ('otchestvo', models.CharField(help_text='Отчество', max_length=50)),
            ],
            options={
                'verbose_name': 'Teacher',
                'ordering': ['familiya', 'imya', 'otchestvo'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название предмета', max_length=100)),
                ('room', models.TextField(help_text='Номер аудитории', max_length=100)),
                ('teacher', models.ForeignKey(help_text='ФИО преподавателя', on_delete=django.db.models.deletion.CASCADE, to='timetable.teachers')),
            ],
            options={
                'verbose_name': 'Lesson',
                'ordering': ['title'],
            },
        ),
    ]
