# Generated by Django 4.1.7 on 2023-04-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0004_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название мероприятия', max_length=100)),
                ('date', models.DateField(help_text='Дата мероприятия')),
            ],
            options={
                'verbose_name': 'Events',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Статус задачи', max_length=100)),
            ],
            options={
                'verbose_name': 'Task status',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название задачи', max_length=100)),
                ('description', models.TextField(help_text='Задача', max_length=100)),
                ('deadline', models.DateField(help_text='Дедлайн задачи')),
                ('owner', models.ForeignKey(help_text='Ответственный за задачу', on_delete=django.db.models.deletion.CASCADE, to='timetable.users')),
                ('status', models.ForeignKey(help_text='Статус задачи', on_delete=django.db.models.deletion.CASCADE, to='tasks.task_status')),
            ],
            options={
                'verbose_name': 'Task',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task_visitors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(help_text='Название задачи', max_length=100)),
                ('visitor_id', models.ForeignKey(help_text='id ответственного', on_delete=django.db.models.deletion.CASCADE, to='timetable.users')),
            ],
            options={
                'verbose_name': 'Task visitor',
                'ordering': ['task'],
            },
        ),
    ]
