# Generated by Django 4.1.7 on 2023-04-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status_id_alter_task_visitors_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(help_text='Статус задачи', on_delete=django.db.models.deletion.CASCADE, to='tasks.task_status'),
        ),
    ]
