# Generated by Django 4.1.7 on 2023-04-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['title'], 'verbose_name': 'Events'},
        ),
    ]
