# Generated by Django 4.1.7 on 2023-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_events_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(help_text='Дата мероприятия'),
        ),
    ]
