# Generated by Django 4.1.7 on 2023-03-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_userroles'),
        ('chat', '0002_alter_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название', max_length=100)),
                ('owner', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='timetable.users')),
            ],
            options={
                'verbose_name': 'Group chat',
            },
        ),
        migrations.CreateModel(
            name='ListMsg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(help_text='Дата отправления')),
                ('time', models.TimeField(help_text='Время отправления')),
                ('message', models.TextField(help_text='Сообщение...', max_length=100)),
                ('chat', models.ForeignKey(help_text='Групповой чат', on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat')),
                ('user_id', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='timetable.users')),
            ],
            options={
                'verbose_name': 'ListMsg',
            },
        ),
        migrations.CreateModel(
            name='ListGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(help_text='Групповой чат', on_delete=django.db.models.deletion.CASCADE, to='chat.groupchat')),
                ('user_id', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='timetable.users')),
            ],
            options={
                'verbose_name': 'list group',
            },
        ),
    ]
